kind: "AdminExtension"
title: "Applications"
description: "The Applications section, provided to app-settings as an extension"
allow:
  - "role:system.admin"
interfaces:
  - "settings.section"
config:
  order: 1
  path: "applications"
